server:
  port: 9000

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-only
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/flipkart"
    username: root
    password: root